name: CMake netnexus

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        build_type: [Debug, Release]
    
    name: Build (${{ matrix.build_type }})

    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libglib2.0-dev libxml2-dev libsqlite3-dev libsnmp-dev snmp

    - name: Configure CMake
      run: |
        if [ "${{ matrix.build_type }}" = "Debug" ]; then
          enable_asan=ON
        else
          enable_asan=OFF
        fi
        cmake -B ${{github.workspace}}/build \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -DENABLE_ASAN=${enable_asan}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{ matrix.build_type }}
